  services:
    - type: web
      name: finlytics-dashboard
      env: python
      buildCommand: "pip install -r requirements.txt"
      startCommand: "python app.py"
      envVars:
        - key: MONGO_URI
          sync: false
        - key: JWT_SECRET_KEY
          sync: false